// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Ristorante.Models
{
    public partial class Piatti
    {
        public string Id { get; set; }
        public string Nome { get; set; }
        public decimal Prezzo { get; set; }
        public string TipoPiatto { get; set; }

        public virtual TipoPiatto TipoPiattoNavigation { get; set; }
    }
}