// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Ristorante.Models
{
    public partial class Piatti
    {
        public string id { get; set; }
        public string Nome { get; set; }
        public decimal Prezzo { get; set; }
        public string Tipo_piatto { get; set; }
    }
}