// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Ristorante.Models
{
    public partial class Prenotazioni
    {
        public DateTime Data { get; set; }
        public int IdUtente { get; set; }
        public int NumeroPersone { get; set; }
        public int IdPrenotazione { get; set; }

        public virtual Utenti IdUtenteNavigation { get; set; }
    }
}