// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Ristorante.Models
{
    public partial class Prenotazione
    {
        public DateTime data { get; set; }
        public string id_utente { get; set; }
        public int numero_persone { get; set; }
        public int id_prenotazione { get; set; }
        public string numero_tel { get; set; }
        public string orario { get; set; }
    }
}