// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Ristorante.Models
{
    public partial class TipoPiatto
    {
        public TipoPiatto()
        {
            Piatti = new HashSet<Piatti>();
        }

        public string TipoPiatto1 { get; set; }
        public string Descrizione { get; set; }

        public virtual ICollection<Piatti> Piatti { get; set; }
    }
}