// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Ristorante.Models
{
    public partial class Utenti
    {
        public Utenti()
        {
            Prenotazioni = new HashSet<Prenotazioni>();
        }

        public int IdUtente { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }

        public virtual ICollection<Prenotazioni> Prenotazioni { get; set; }
    }
}