// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Ristorante.Models
{
    public partial class Utente
    {
        public Utente()
        {
            Prenotazioni = new HashSet<Prenotazioni>();
        }

        public int id_utente { get; set; }
        public string username { get; set; }
        public string password { get; set; }

        public virtual ICollection<Prenotazioni> Prenotazioni { get; set; }
    }
}