// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Ristorante.Models;

#nullable disable

namespace Ristorante.Data
{
    public partial class RistoranteContext : DbContext
    {
        public RistoranteContext()
        {
        }

        public RistoranteContext(DbContextOptions<RistoranteContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Piatti> Piatti { get; set; }
        public virtual DbSet<Prenotazioni> Prenotazioni { get; set; }
        public virtual DbSet<TipoPiatto> TipoPiatto { get; set; }
        public virtual DbSet<Utenti> Utenti { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Latin1_General_CI_AS");

            modelBuilder.Entity<Piatti>(entity =>
            {
                entity.Property(e => e.Id)
                    .HasMaxLength(10)
                    .HasColumnName("id")
                    .IsFixedLength(true);

                entity.Property(e => e.Nome)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Prezzo).HasColumnType("decimal(5, 2)");

                entity.Property(e => e.TipoPiatto)
                    .IsRequired()
                    .HasMaxLength(25)
                    .HasColumnName("Tipo_piatto");

                entity.HasOne(d => d.TipoPiattoNavigation)
                    .WithMany(p => p.Piatti)
                    .HasForeignKey(d => d.TipoPiatto)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Piatti_Tipo_piatto");
            });

            modelBuilder.Entity<Prenotazioni>(entity =>
            {
                entity.HasKey(e => e.IdPrenotazione);

                entity.Property(e => e.IdPrenotazione)
                    .ValueGeneratedNever()
                    .HasColumnName("id_prenotazione");

                entity.Property(e => e.Data)
                    .HasColumnType("datetime")
                    .HasColumnName("data");

                entity.Property(e => e.IdUtente).HasColumnName("id_utente");

                entity.Property(e => e.NumeroPersone).HasColumnName("numero_persone");

                entity.HasOne(d => d.IdUtenteNavigation)
                    .WithMany(p => p.Prenotazioni)
                    .HasForeignKey(d => d.IdUtente)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Prenotazioni_Utenti");
            });

            modelBuilder.Entity<TipoPiatto>(entity =>
            {
                entity.HasKey(e => e.TipoPiatto1);

                entity.ToTable("Tipo_Piatto");

                entity.Property(e => e.TipoPiatto1)
                    .HasMaxLength(25)
                    .HasColumnName("Tipo_piatto");

                entity.Property(e => e.Descrizione)
                    .IsRequired()
                    .HasMaxLength(25);
            });

            modelBuilder.Entity<Utenti>(entity =>
            {
                entity.HasKey(e => e.IdUtente);

                entity.Property(e => e.IdUtente)
                    .ValueGeneratedNever()
                    .HasColumnName("id_utente");

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(12)
                    .HasColumnName("password");

                entity.Property(e => e.Username)
                    .IsRequired()
                    .HasMaxLength(25)
                    .HasColumnName("username");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}